export const LOGOUT = 'LOGOUT'
export const SET_USER_DATA = 'SET_USER_DATA'
export const SET_GIFT_ITEMS = 'SET_GIFT_ITEMS'
export const SET_OVERVIEW = 'SET_OVERVIEW'
export const SET_HISTORY = 'SET_HISTORY'